<?php
get_header();
get_template_part('template/new-home/index');
get_template_part('template/new-home/section-1');
get_template_part('template/new-home/section-2');
get_template_part('template/new-home/section-3');
get_template_part('template/new-home/section-4');
get_template_part('template/new-home/section-5');
get_template_part('template/new-home/section-6');
get_footer();
?>
